version: 0.2
phases:
  install:
    commands:
      - echo Installing source dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync dist/ s3://codepipeline-ap-northeast-1-256408389900/
